const data = [
  { id: 1, name: 'Engine', uniqueNumber: 'ENG123', canAssignQuantity: false },
  { id: 2, name: 'Passenger Car', uniqueNumber: 'PAS456', canAssignQuantity: false },
  { id: 3, name: 'Freight Car', uniqueNumber: 'FRT789', canAssignQuantity: false },
  { id: 4, name: 'Wheel', uniqueNumber: 'WHL101', canAssignQuantity: true, quantity: 87 },
  { id: 5, name: 'Seat', uniqueNumber: 'STS234', canAssignQuantity: true, quantity: 42 },
  { id: 6, name: 'Window', uniqueNumber: 'WIN567', canAssignQuantity: true, quantity: 19 },
  { id: 7, name: 'Door', uniqueNumber: 'DR123', canAssignQuantity: true, quantity: 33 },
  { id: 8, name: 'Control Panel', uniqueNumber: 'CTL987', canAssignQuantity: true, quantity: 12 },
  { id: 9, name: 'Light', uniqueNumber: 'LGT456', canAssignQuantity: true, quantity: 65 },
  { id: 10, name: 'Brake', uniqueNumber: 'BRK789', canAssignQuantity: true, quantity: 28 },
  { id: 11, name: 'Bolt', uniqueNumber: 'BLT321', canAssignQuantity: true, quantity: 91 },
  { id: 12, name: 'Nut', uniqueNumber: 'NUT654', canAssignQuantity: true, quantity: 76 },
  { id: 13, name: 'Engine Hood', uniqueNumber: 'EH789', canAssignQuantity: false },
  { id: 14, name: 'Axle', uniqueNumber: 'AX456', canAssignQuantity: false },
  { id: 15, name: 'Piston', uniqueNumber: 'PST789', canAssignQuantity: false },
  { id: 16, name: 'Handrail', uniqueNumber: 'HND234', canAssignQuantity: true, quantity: 54 },
  { id: 17, name: 'Step', uniqueNumber: 'STP567', canAssignQuantity: true, quantity: 37 },
  { id: 18, name: 'Roof', uniqueNumber: 'RF123', canAssignQuantity: false },
  { id: 19, name: 'Air Conditioner', uniqueNumber: 'AC789', canAssignQuantity: false },
  { id: 20, name: 'Flooring', uniqueNumber: 'FLR456', canAssignQuantity: false },
  { id: 21, name: 'Mirror', uniqueNumber: 'MRR789', canAssignQuantity: true, quantity: 23 },
  { id: 22, name: 'Horn', uniqueNumber: 'HRN321', canAssignQuantity: false },
  { id: 23, name: 'Coupler', uniqueNumber: 'CPL654', canAssignQuantity: false },
  { id: 24, name: 'Hinge', uniqueNumber: 'HNG987', canAssignQuantity: true, quantity: 48 },
  { id: 25, name: 'Ladder', uniqueNumber: 'LDR456', canAssignQuantity: true, quantity: 15 },
  { id: 26, name: 'Paint', uniqueNumber: 'PNT789', canAssignQuantity: false },
  { id: 27, name: 'Decal', uniqueNumber: 'DCL321', canAssignQuantity: true, quantity: 62 },
  { id: 28, name: 'Gauge', uniqueNumber: 'GGS654', canAssignQuantity: true, quantity: 31 },
  { id: 29, name: 'Battery', uniqueNumber: 'BTR987', canAssignQuantity: false },
  { id: 30, name: 'Radiator', uniqueNumber: 'RDR456', canAssignQuantity: false },
];

export default data;
